---
date: "2026-07-02"
image-alt: "Prosedur pengajuan perpanjangan tugas belajar / izin belajar."
listing: false
toc: false
---

## Perpanjangan Tugas Belajar / Izin Belajar {.unnumbered}

Bagi mahasiswa yang masa **Tugas Belajar** atau **Izin Belajar** dari instansi asal telah berakhir dan memerlukan surat perpanjangan, silakan mengikuti prosedur berikut:

1.  Kirimkan permohonan melalui email ke [**teti\@ugm.ac.id**](mailto:teti@ugm.ac.id) dengan subjek:

**Perpanjangan Tugas Belajar / Izin Belajar – \[Nama Mahasiswa\]**

2.  Pada isi email, cantumkan informasi berikut:

-   Nama

-   NIM

-   Program Studi

-   Semester yang diajukan untuk perpanjangan

-   Tujuan surat, meliputi:

    -   Nama Pejabat/Jabatan/Divisi

    -   Nama Instansi

    -   Alamat lengkap instansi

3.  Lampirkan dokumen berikut:

-   **SK Tugas Belajar** atau **Surat Izin Belajar** dari instansi asal yang mencantumkan masa berlaku tugas/izin belajar.

-   **Kartu Hasil Studi (KHS)** terakhir.

-   **Laporan Kemajuan Studi**.

Mohon memastikan seluruh informasi dan dokumen pendukung telah lengkap agar proses penerbitan surat dapat dilakukan dengan tepat.


