---
date: "2026-07-07"
image-alt: "Prosedur pengajuan izin penelitian / pengambilan data."
listing: false
toc: false
---

## Pengajuan Aktivitas dan Prestasi pada SKPI (SIMASTER) {.unnumbered}

Mahasiswa yang akan mengajukan **prestasi, sertifikasi, maupun aktivitas kemahasiswaan** agar dapat dicantumkan pada **Surat Keterangan Pendamping Ijazah (SKPI)**, silakan mengikuti prosedur berikut:

1.  Login ke **SIMASTER**, kemudian ajukan aktivitas pada menu **Aktivitas Mahasiswa**.

-   Lengkapi seluruh informasi yang diminta.

-   Unggah dokumen pendukung/bukti kegiatan.

-   Pastikan memilih **peran (role)** yang sesuai dengan aktivitas yang diajukan.

2.  Setelah pengajuan dilakukan di SIMASTER, kirimkan konfirmasi melalui email ke [**akademik.ft\@ugm.ac.id**](mailto:akademik.ft@ugm.ac.id) dengan subjek:\
    **Konfirmasi Aktivitas Mahasiswa**

Cantumkan informasi berikut pada email:

-   Nama

-   NIM

-   Program Studi

-   Cuplikan (*screenshot*) daftar aktivitas yang telah diajukan di SIMASTER.

3.  Prosedur lengkap mengenai pengajuan aktivitas pada SKPI dapat dilihat pada panduan **Pengajuan Aktivitas di SKPI** : <https://ft.ugm.ac.id/prosedur-pengajuan-aktivitas-mahasiswa-di-skpi/>