---
date: "2026-07-08"
image-alt: "Prosedur pengajuan izin cuti kuliah."
listing: false
toc: false
---

## Pengambilan Dokumen Wisuda {.unnumbered}

Dokumen wisuda meliputi **Ijazah, Transkrip Akademik, SKPI, Terjemahan Transkrip,** dan **Sertifikat Cum Laude** dapat diambil dengan ketentuan sebagai berikut:

### Pengambilan oleh Lulusan {.unnumbered}

Dokumen wisuda dapat diambil **setelah pelaksanaan Wisuda UGM** di: **Unit Layanan Terpadu (ULT) -** Gedung **SGLC Fakultas Teknik UGM Lantai 2**

### Pengambilan Melalui Kuasa {.unnumbered}

Apabila lulusan berhalangan mengambil dokumen secara langsung, pengambilan dapat diwakilkan dengan prosedur berikut:

1.  Unduh dan isi **Surat Kuasa** pada tautan berikut:\
    <https://diska.ugm.ac.id/s/GkFe4ZxDmcsTmQz+>
2.  Surat kuasa harus:
    -   Dibubuhi materai.
    -   Ditandatangani oleh **Pemberi Kuasa (Pemilik Dokumen)** dan **Penerima Kuasa**.
    -   Memuat identitas lengkap kedua belah pihak (Nama, Alamat, NIM/Program Studi untuk lulusan, serta NIK).
3.  Pemberi kuasa mengirimkan dokumen berikut ke [**akademik.ft\@ugm.ac.id**](mailto:akademik.ft@ugm.ac.id) menggunakan **email UGM**, dengan melampirkan:
    -   Surat kuasa yang telah diisi dan ditandatangani.
    -   Bukti pengembalian toga (dapat diunduh melalui SIMASTER).
    -   Fotokopi identitas pemberi kuasa dan penerima kuasa (berwarna maupun hitam putih diperbolehkan).
4.  Surat kuasa **asli** diserahkan kepada penerima kuasa.
5.  Penerima kuasa datang ke **ULT Gedung SGLC FT UGM Lantai 2** dengan membawa surat kuasa asli.
6.  Petugas ULT akan melakukan verifikasi dengan mencocokkan surat kuasa asli yang dibawa penerima kuasa dengan dokumen yang telah dikirim melalui email. Apabila seluruh dokumen telah sesuai dan lolos verifikasi, dokumen wisuda akan diserahkan kepada penerima kuasa.