## Usulan dan Pelaksanaan Penelitian Tesis

Berikut ini adalah SOP penyusunan usulan penelitian dan pelaksanaan tesis di Program Magister Teknologi Informasi FT UGM:

a.  Tahapan yang harus dilalui oleh mahasiswa untuk mulai mengerjakan tesis adalah dengan pertama kali mengajukan judul tesis kepada calon dosen pembimbing tesisnya pada semester 2, atau judul berasal dari calon dosen pembimbing yang merupakan bagian dari penelitian dosen tersebut. Judul tesis mahasiswa harus disetujui oleh calon dosen pembimbing untuk kemudian menjadi dosen pembimbing tesis.

b.  Untuk mempertajam judul dan fokus penelitian, mahasiswa harus melakukan seminar penelitian tesis.

c.  Seminar I lebih diarahkan untuk melihat hasil studi mandiri mahasiswa ketika mereka mempersiapkan topik penelitian. Dalam seminar ini mahasiswa mempresentasikan hasil telaah riset (paper terpublikasi) atau literatur lainnya.

d.  Seminar II yang dilaksanakan pada semester III merupakan kelanjutan dari Seminar I. Seminar I merupakan prasyarat untuk mengambil Seminar II. Pada Seminar II mahasiswa harus mempresentasikan kemajuan risetnya.  Seminar II dihadiri oleh dosen penguji.  Setiap mahasiswa yang mengambil tesis harus menghadiri 80% dari jumlah seminar dalam bidangnya dan menghadiri 20% dari jumlah seminar yang relevan di luar bidangnya.

e.  Disamping itu, pelaksanaan penelitian tesis dilakukan dengan konsultasi/seminar internal oleh mahasiswa dengan dosen pembimbingnya.

Untuk menjamin efektifitas pelaksanaan monitoring dan evaluasi, pengelola program studi dapat memantau jalannya proses pembimbingan tesis melalui Form Konsultasi Pembimbingan Tesis pada program Magisterxz. Selain itu secara berkala pengelola program studi mengadakan pertemuan dengan mahasiswa untuk memonitor kemajuan pelaksanaan penelitian tesis. Apabila ada permasalahan, pengelola program studi dapat membantu mencari solusi.

Untuk mendeteksi kemungkinan penyimpangan dalam pelaksanaan penelitian tesis dilakukan mekanisme monitoring dan evaluasi dibawah koordinasi tim penjaminan mutu tesis sebagai berikut:

-   Monitoring dan evaluasi usulan penelitian melalui *peer review* proposal penelitian dan diplenokan dalam rapat dosen Program Studi Magister Teknologi Informasi. Selain itu mahasiswa diwajibkan presentasi usulan penelitian dalam mata kuliah Seminar 1 sehingga dapat dideteksi apabila ada indikasi penyimpangan.

-   Apabila ada indikasi penyimpangan terhadap usulan penelitian, maka indikasi tersebut disampaikan kepada mahasiswa dan calon pembimbing. Selanjutnya mahasiswa diwajibkan untuk memperbaiki usulan penelitian tersebut dibawah supervisi pembimbing. Penyimpangan yang mungkin terjadi antara lain sebagai berikut:

    -   adanya ketidaksesuaian landasan filosofis penelitian dengan topik penelitian

    -   metode penelitian yang kurang tepat

    -   kemungkinan duplikasi topik penelitian dengan hasil penelitian yang sudah ada

-   Monitoring dan evaluasi pelaksanaan penelitian untuk mencegah penyimpangan dilakukan oleh tim penjaminan mutu tesis dengan menilai:

    -   Kesesuaian format tesis dengan format yang ditetapkan,

    -   Konsistensi data dan informasi yang digunakan.

    -   Keterlibatan dosen pembimbing membaca dengan teliti draf tesis.

-   Pelaksanaan monitoring dan evaluasi pelaksanaan penelitian dilakukan dalam tahapan sebagai berikut:

    -   Seminar internal di laboratorium dibawah pengawasan pembimbing tesis

    -   Presentasi dan diskusi dalam mata kuliah Seminar 2

    -   Publikasi dalam seminar/forum ilmiah skala nasional atau internasional

    -   Evaluasi saat ujian pra pendadaran

    -   Evaluasi saat ujian tesis/pendadaran