## Penulisan Tesis

Proses penulisan tesis dilakukan sesuai dengan SOP proses penulisan tesis sebagai berikut:

a.  Proses penulisan tesis dimulai sejak mahasiswa melakukan penelitian tesis. Dalam proses ini, di Semester III mahasiswa harus mempresentasikan kemajuan risetnya pada mata kuliah Seminar 2. 

b.  Mahasiswa intensif melakukan penelitian dan menulis tesis ketika berada di semester akhir (semester IV). Dalam kurikulum Program Studi Magister Teknologi Informasi FT UGM, pada semester ini tidak ada mata kuliah yang diambil sehingga mahasiswa fokus pada penelitian tesisnya.

c.  Penulisan tesis harus sudah selesai sebulan sebelum semester berakhir. Akan ada pengumuman atau jadwal dari program studi untuk pengumpulan naskah tesis, untuk kemudian dijadwalkan ujian tesis.

Untuk menjamin efektifitas pelaksanan monitoring dan evaluasi penulisan tesis, pengelola program studi dapat memantau jalannya proses penulisan melalui laporan tim penjaminan mutu tesis. Apabila terjadi permasalahan dapat segera dicarikan jalan keluarnya oleh tim penjaminan mutu tesis dan pembimbing.

Untuk mendeteksi kemungkinan penyimpangan dalam penulisan tesis dilakukan mekanisme monitoring dan evaluasi dibawah koordinasi tim penjaminan mutu tesis sebagai berikut:

-   Monitoring dan evaluasi penulisan tesis untuk mencegah penyimpangan dilakukan oleh tim penjaminan mutu tesis dengan menilai:

    -   Kesesuaian format tesis dengan format yang ditetapkan,

    -   Konsistensi data dan informasi yang digunakan.

    -   Keterlibatan dosen pembimbing membaca dengan teliti draf tesis.

-   Pelaksanaan monitoring dan evaluasi penulisan tesis dilakukan dalam tahapan sebagai berikut:

    -   Seminar internal di laboratorium dibawah pengawasan pembimbing tesis

    -   Presentasi dan diskusi dalam mata kuliah Seminar 2

    -   Evaluasi saat ujian pra pendadaran

    -   Evaluasi saat ujian tesis/pendadaran