## Dosen Pembimbing dan Proses Pembimbingan

Proses pembimbingan tesis dilakukan sesuai dengan SOP persyaratan dosen pembimbing penelitian tesis  di  Program Studi Magister Teknologi Informasi FT UGM adalah sebagai berikut:

1.  Dosen Departemen Teknik Elektro dan Teknologi Informasi Fakultas Teknik Universitas Gadjah Mada

2.  Dosen berpendidikan doktor atau yang sederajat. Dalam kasus khusus, dimungkinkan dosen yang berjenjang pendidikan master untuk ikut membimbing di Program Studi Magister Teknologi Informasi jika memenuhi syarat sesuai dengan peraturan dari Universitas Gadjah Mada dan/atau Peraturan Pemerintah.

3.  Bidang penelitian dosen sesuai dengan bidang penelitian tesis yang akan dibimbing.

4.  Dosen dari luar Departemen Teknik Elektro dan Teknologi Informasi Fakultas Teknik Universitas Gadjah Mada dapat menjadi pembimbing tesis dengan syarat memiliki pendidikan berjenjang doktor atau yang sederajat, memiliki pengalaman penelitian sesuai bidang dengan penelitian yang akan dibimbing. Syarat lain yang harus dipenuhi oleh dosen dari luar Departemen Teknik Elektro dan Teknologi Informasi, yaitu:

    a.  Pengalaman mengajar

    b.  Pengalaman penelitian

    c.  Pengalaman lapangan sebagai praktisi

Adapun **SOP** proses pembimbingan tesis adalah sebagai berikut:

a.  Dosen pembimbing memberikan layanan konsultasi dan pendampingan kepada mahasiswa selama menyusun proposal penelitian tesis. Layanan konsultasi juga diberikan saat mahasiswa melakukan revisi proposal penelitian.

b.  Dosen pembimbing utama dan pendamping bekerja sama secara intensif melakukan supervisi terhadap pelaksanaan penelitian tesis mahasiswa dan secara periodis melakukan seminar internal sebagai mekanisme monitoring dan evaluasi penelitian tesis mahasiswa.

c.  Dosen pembimbing utama dan pendamping bekerja sama secara intensif membimbing mahasiswa menulis naskah publikasi yang akan diseminarkan di level nasional dan internasional.

d.  Dosen pembimbing utama dan pendamping bekerja sama secara intensif melakukan bimbingan dan bantuan teknis penulisan tesis mengikuti SOP yang belaku.

e.  Dosen pembimbing utama dan pendamping bekerja sama secara intensif melakukan monitoring dan evaluasi penulisan tesis secara berkala mengikuti SOP yang belaku.

f.  Tim penjaminan mutu tesis bersama pengelola program studi melakukan evaluasi terhadap proses pembimbingan tesis.

Untuk menjamin efektifitas pelaksanan monitoring dan evaluasi penulisan tesis, pengelola program studi dapat memantau jalannya proses pembimbingan tesis melalui laporan tim penjaminan mutu tesis. Apabila terjadi permasalahan dapat segera dicarikan jalan keluarnya bersama tim penjaminan mutu tesis.

Untuk mendeteksi kemungkinan penyimpangan dalam pembimbingan tesis dilakukan mekanisme monitoring dan evaluasi dibawah koordinasi tim penjaminan mutu tesis sebagai berikut:

-   Monitoring dan evaluasi pembimbingan tesisuntuk mencegah penyimpangan dengan menilai:

    -   Kewajaran jumlah mahasiswa yang menjadi beban dosen pembimbing tesis.

    -   Kesesuaian standar kualifikasi keilmuan dosen pembimbing

    -   Aktif tidaknya dosen pembimbing melaksanakan tugas-tugas pembimbingan sesuai dengan ketentuan

-   Pelaksanaan monitoring dan evaluasi pembimbingan tesisdilakukan oleh tim penjaminan mutu tesis dalam tahapan sebagai berikut:

    -   Komunikasi rutin pengelola program studi dengan mahasiswa terkait kemajuan penelitian tesis

    -   Komunikasi rutin pengelola program studi dengan pembimbing terkait kemajuan penelitian tesis mahasiswanya

    -   Evaluasi rutin per semester terhadap waktu pembimbingan dikaitkan dengan progres kemajuan penetian tesis mahasiswa

    -   Mengusulkan tindak lanjut ke forum rapat dosen apabila terjadi penyimpangan

    -   Rapat dosen untuk menentukan tindak lanjut apabila ada penyimpangan

    -   Program studi mengeksekusi tindak lanjut yang telah diputuskan di rapat dosen