## Tahapan Setelah Sidang Pendadaran

1.  Setelah Menyelesaikan pendadaran mahasiswa diharapkan langsung melakukan revisi sesuai masukan dari Penguji dan Pembimbing saat sidang Pendadaran.

<!-- -->

2.  Segera konsultasikan hasil revisi untuk mendapatkan persetujuan (jika memang sudah layak dan sesuai dengan ekspektasi penguji dan pembimbing)

3.  Jika dirasa sudah cukup, dan seluruh dosen penguji dan pembimbing Acc atas hasil revisi anda, maka silakan mendaftar proses yudisium yang akan terjadwal secara berkala setiap hari Senin setiap bulannya. **PENDAFTARAN Yudisium Maksimal hari RABU, sebelum pelaksanaan yudisium pada hari SENIN.**

<!-- -->

4.  Jika dalam proses yudisium anda dinyatakan lulus, baik dari sisi administrasi maupun akademik maka proses selanjutnya adalah anda **MENUNGGU lembar pengesahan tesis** yang akan diberikan oleh bagian akademik Pascasarjana melalui email masing-masing yang sudah tertandatangani oleh seluruh dosen dan Ketua Departemen.

<!-- -->

5.  Setelah menerima lembar pengesahan tersebut mahasiswa baru dapat bergerak untuk mencari syarat lain seperti ETD Unggah Mandiri pada perpustakaan Universitas Gadjah Mada. **Jika anda unggah ETD pada hari terakhir, INGAT untuk cut off lapor ke Prodi adalah jam 14.00 WIB (Jika anda lapor jam 15.00 WIB maka dipastikan tidak akan terangkut ke daftar wisudawan terdekat).**

<!-- -->

6.  Setelah ETD selesai maka segera lakukan **daftar Pra Wisuda (Account Wisuda)** melalui akun magister masing-masing sesuai dengan timeline yang ada. \*) Untuk pendaftaran akun proses selanjutnya tidak perlu menunggu verifikasi, bisa dilakukan paralel dengan Jadwal lain dengan catatan telah selesai mengunggah seluruh syarat sesuai timeline yang ada.

<!-- -->

7.  Setelah ETD selesai segera lengkapi syarat wisuda melalui [**TAUTAN G-FORM BERIKUT**](https://docs.google.com/forms/d/e/1FAIpQLScBsjS1b7BhYdZtSlhTyBPk8p_lnZ7KUBzoFTaiLJdxdUdVLg/viewform)

<!-- -->

8.  Jangan lupa mengisi data SIMASTER, **khususnya isian Gama Co-Brand dan Exit Survey,** karena jika keduanya belum diisi pada periode yang ditentukan maka proses pemberkasan tidak dapat dilakukan. **Untuk bisa mengisi poin 8 ini menunggu koordinasi dari Pak Dulhadi.**

<!-- -->

9.  Jangan lupa mengisi SKPI di Simaster (WAJIB), masukkan semua bukti publikasi sebagai capaian pendukung di SIMASTER. [**Tata cara pengisian ikuti sesuai FT UGM (klik di sini).**](https://ft.ugm.ac.id/prosedur-pengajuan-aktivitas-mahasiswa-di-skpi/)

::: callout-important 
## Catatan

Seluruh proses yang sudah dilalui dimungkinkan gagal dan dibatalkan jika ternyata dikemudian hari ditemukan adanya pelanggaran etika (misal memalsu dokumen, memalsu tanda tangan, dan perbuatan-perbuatan mal-administrasi lain yang secara sengaja dilakukan).

Dalam proses menuju finalisasi transkrip dan ijazah akan banyak sekali komunikasi dan kerja sama yang harus dilakukan antara Prodi dan Mahasiswa (ini terjadi tidak hanya di prodi ini saja, melainkan secara umum di UGM). Mohon pintu komunikasi dibuka seluas-luasnya karena perlu responsif dan sigap. Proses ini melibatkan banyak pihak sampai dengan PDDIKTI untuk penerbitan nomor PIN. Sebelumnya kami mohon maaf jika prosesnya akan sedikit berbelit dan ribet karena secara komunikasi data dari Mhs - Prodi - Univ - dan PDDIKTI masih terus dalam proses penyempurnaan. Mari kita lalui bersama semua tahapannya sehingga bisa sempurna dalam proses penerbitan transkrip dan ijazah.

:::