---
date: "2026-07-07"
image-alt: "Prosedur pengajuan surat pengembalian ke instansi asal."
listing: false
toc: false
---

## Surat Pengembalian ke Instansi Asal {.unnumbered}

Bagi mahasiswa yang memerlukan **Surat Pengembalian ke Instansi Asal** setelah menyelesaikan studi, silakan mengikuti prosedur berikut:

1.  Kirimkan permohonan melalui email ke [**teti\@ugm.ac.id**](mailto:teti@ugm.ac.id) dengan subjek:

**Surat Pengembalian ke Instansi Asal – \[Nama Mahasiswa\]**

-   Pada isi email, cantumkan informasi berikut:
-   Nama
-   NIM
-   Program Studi
-   Tujuan surat, meliputi:
    -   Nama Pejabat/Jabatan/Divisi

    -   Nama dan Alamat Instansi

3.  Lampirkan dokumen pendukung sesuai status kelulusan:
4.  **Bagi yang sudah wisuda:** Ijazah.
5.  **Bagi yang belum wisuda:**
    -   Surat Keterangan Yudisium.

    -   Lembar Pengesahan Tesis.

    -   Bukti Pendaftaran Wisuda di SIMASTER.
6.  Mohon memastikan seluruh informasi dan lampiran telah lengkap agar surat dapat diproses dengan tepat.
