## Sistem Kredit Semester

### Pengertian

Dalam sistem kredit beban studi yang harus diselesaikan oleh mahasiswa pada suatu jenjang studi dinyatakan dalam bentuk sejumlah satuan kredit.

Berdasarkan adanya perbedaan minat, bakat dan kemampuan antara mahasiswa yang satu dengan yang lain, maka baik cara dan waktu untuk menyelesaikan beban studi maupun komposisi kegiatan studi untuk memenuhi beban studi yang diwajibkan tidak harus sama bagi setiap mahasiswa, meskipun  mereka  duduk  dalam  jenjang  pendidikan yang sama.

### Tujuan

Pada dasarnya tujuan pokok penggunaan sistem kredit ialah:

1.  Untuk memberikan kesempatan kepada para mahasiswa yang cakap dan giat belajar agar dapat menyelesaikan studi dalam waktu yang sesingkat-singkatnya;

2.  Untuk memberikan kesempatan pada para mahasiswa agar dapat mengikuti kegiatan pendidikan yang sesuai dengan minat, bakat dan kemampuan;

3.  Untuk melaksanakan sejauh mungkin sistem pendidikan “input” dan “output” ganda;

4.  Untuk mempermudah penyesuaian kurikulum terhadap perkembangan ilmu dan teknologi;

5.  Untuk memperbaiki sistem evaluasi kecakapan mahasiswa.

### Ciri-ciri

Untuk memberikan pengertian yang jelas mengenai sistem kredit, perlu dikemukakan ciri-ciri yang terdapat pada sistem ini:

1.  Dalam sistem kredit bobot tiap-tiap mata kuliah dihargai dengan satuan kredit.

2.  Besar satuan kredit untuk kegiatan pendidikan yang berlainan tidak perlu sama.

3.  Besar satuan kredit untuk masing-masing kegiatan pendidikan didasarkan atas banyaknya jam kegiatan yang digunakan setiap minggu untuk kegiatan tersebut.

4.  Kegiatan pendidikan yang disediakan terdiri atas kegiatan wajib dan pilihan. Kegiatan pendidikan wajib adalah kegiatan yang wajib diikuti semua mahasiswa dalam jenjang pendidikan tertentu. Kegiatan pendidikan pilihan adalah kegiatan pendidikan yang disediakan untuk memenuhi beban pendidikan yang diwajibkan  dan  merupakan  saluran  minat,  bakat dan kemampuan masing-masing mahasiswa dalam jenjang pendidikan tertentu.

5.  Dalam batas tertentu mahasiswa mendapatkan kebebasan untuk menentukan:

    -   banyaknya satuan kredit yang diambil untuk tiap-tiap semester;

    -   jenis kegiatan studi yang diambil untuk tiap-tiap semester;

    -   jangka waktu untuk menyelesaikan beban studi yang diwajibkan.

6.  Banyaknya satuan kredit yang diambil oleh mahasiswa pada semester tertentu  ditentukan antara lain oleh kemampuan studi pada semester-semester sebelumnya, keadaan sosial ekonomi dan pribadi mahasiswa yang bersangkutan.

### Pengisian Kartu Rencana Studi

Pendaftaran kegiatan pendidikan dilakukan oleh mahasiswa dengan mengisi Kartu Rencana Studi secara *on-line*, mengambil password di bagian pengajaran dengan menyerahkan fotocopi bukti pembayaran SPP.

### Tata Cara Pengisian KRS

Tata cara pengisian KRS diatur oleh Departemen sebagai berikut:

a.  Pengambilan *password*, pengisian dan pengambilan print out KRS harus sesuai jadwal yang telah ditentukan oleh Departemen. Apabila terlambat dari waktu yang telah ditentukan, mahasiswa dikenakan denda keterlambatan pengisian KRS.

b.  Dalam pengisian KRS, penulisan kode matakuliah harus cermat. Apabila terjadi kesalahan penulisan kode matakuliah dalam KRS merupakan tanggung jawab mahasiswa bersangkutan.

c.  Pengambilan SKS tidak boleh melebihi jumlah SKS yang telah ditentukan, sesuai dengan Indeks Prestasi (IP) yang diperoleh pada semester sebelumnya. Apabila terjadi kelebihan SKS yang diambil, maka Departemen berhak membatalkan kelebihan jumlah SKS matakuliah, sesuai pilihan mahasiswa.

d.  *Print out* KRS disahkan oleh Dosen PA. 1 lembar untuk dosen Pembimbing akademik, 1 lembar untuk mahasiswa.

### Pengubahan Matakuliah

Tidak ada pengubahan matakuliah dalam Kartu Rencana Studi.

### Pembatalan Rencana Studi

Matakuliah yang telah tertulis di dalam KRS dapat dibatalkan karena mahasiswa merasa tidak sesuai atau tidak mampu menyelesaikan dengan baik. Mahasiswa diberi kesempatan untuk membatalkan matakuliah ke bagian pengajaran dengan membawa bukti KRS yang disahkan oleh Dosen Pembimbing Akademik. Waktu pembatalan matakuliah dilakukan sesuai kalender akademik yang telah ditentukan. Pembatalan matakuliah di luar waktu yang telah ditentukan tidak diijinkan.