## Evaluasi Pelaksanaan Pembelajaran

### Maksud dan Tujuan Penyelenggaraan Ujian (Evaluasi).

Maksud dan tujuan penyelenggaraan ujian:

1.  Untuk menilai apakah seorang mahasiswa telah memahami atau menguasai bahan yang disajikan;

2.  Untuk mengelompokkan mahasiswa berdasarkan tingkat kemampuannya, digunakan kategori nilai sebagai berikut: A (amat baik sekali), A- (amat baik), A/B (antara amat baik dan baik), B+ (baik sekali), B (baik), B- (cukup baik), B/C (antara baik dan cukup), C+ (cukup baik sekali), C (cukup), D (kurang), dan E (sangat kurang).

3.  Untuk menilai apakah bahan yang disajikan telah sesuai serta cara menyajikannya telah cukup baik, sehingga para siswa dengan usaha yang wajar dapat memahami bahan tersebut.

Tujuan pertama dan kedua tersebut terutama ditujukan kepada para mahasiswa. Tujuan ketiga terutama ditujukan kepada bahan kegiatan pendidikan dan dosen.

Sistem ujian dan sistem penilaian harus disesuaikan dengan maksud dan tujuan tersebut, dan penyelenggaraan ujian harus baik.

### Sistem Ujian / Evaluasi

Ujian dapat dilaksanakan dengan berbagai macam cara seperti ujian tertulis, ujian lesan, ujian dalam bentuk seminar, ujian dalam bentuk penulisan karangan dan sebagainya. Ujian dapat pula dilaksanakan dengan berbagai kombinasi cara-cara tersebut. Cara ujian yang digunakan perlu disesuaikan dengan sifat kegiatan pendidikan.

Agar maksud dan tujuan diselenggarakannya ujian dapat tercapai, maka perlu diadakan beberapa kali ujian, yaitu satu kali ujian akhir semester dan sekurang-kurangnya satu kali ujian sisipan. Data nilai dapat diperoleh berdasarkan atas nilai ujian sisipan, ujian akhir semester, dan nilai kegiatan rangkaian, seperti penulisan  karangan, pekerjaan rumah, partisipasi dalam kelas, praktek dan sebagainya.

Nilai akhir yang diberikan kepada mahasiswa ditentukan berdasarkan data nilai tersebut, yang berarti bahwa nilai akhir itu merupakan kesimpulan nilai-nilai yang dicapai oleh mahasiswa dalam ujian akhir dan kegiatan rangkaian. Dalam menentukan nilai akhir, bobot nilai-nilai yang merupakan komponennya perlu ditentukan lebih dahulu dan diberitahukan kepada mahasiswa. Misalnya: nilai ujian akhir 50%; ujian sisipan 25%; nilai penulisan karangan 15%; dan nilai pekerjaan rumah 10%.

Dengan adanya data nilai yang terdiri atas berbagai jenis nilai tersebut, evaluasi hasil studi mahasiswa dalam suatu kegiatan pendidikan dapat dilaksanakan lebih tepat. Sedang adanya beberapa ujian dan penilaian merupakan dorongan bagi para mahasiswa untuk rajian belajar.