### Evaluasi Hasil Studi Akhir Semester

Evaluasi ini dikerjakan pada tiap akhir semester, meliputi semua kegiatan pendidikan yang diambil oleh mahasiswa pada semester itu. Hasil evaluasi ini terutama digunakan untuk menentukan banyaknya sks yang dapat diambil pada semester berikut-nya, dengan mempertimbangkan hasil studi semester-semester sebelumnya.

### Evaluasi Hasil Studi Akhir Program Studi

Jumlah sks minimum yang harus dikumpulkan oleh mahasiswa untuk menyelesaikan jenjang studi Master of Engeneering Program Studi Magister Teknologi Informasi Fakultas Teknik UGM adalah sebesar 40 sks.  Mahasiswa dinyatakan  telah  menyelesaikan  jenjang  program studi Magister Teknologi Informasi Fakultas  Teknik UGM ini apabila memenuhi syarat-syarat

-   SKS yang diperoleh telah minimal adalah 40 SKS (mahasiswa sangat ditekankan  untuk mengambil lebih), dan telah lulus semua mata kuliah wajib dan lulus satu mata kuliah konsentrasi (3 SKS);

-   Tidak ada nilai D;

-   IP Minimal Kelulusan adalah 3.00;

-   Telah menyelesaikan tesis  dan ujian tesis atau pendadaran.

Syarat ujian tesis adalah telah mempublikasikan hasil penelitian/tesis S2-nya. Publikasi berupa ringkasan tesis S2 atau bagian dari tesis/riset S2 dari mahasiswa yang bersangkutan beserta dosen pembimbingnya. Publikasi penelitian ini harus di-*submit* ke seminar atau journal yang berskala nasional/internasional sesuai kriteria. Kriteria minimal adalah dipublikasikan di dalam seminar nasional atau journal ter-akreditasi A, atau daftar seminar/journal yang diakui oleh Program Pasca Sarjana Departemen Teknik Elektro dan Teknologi Informasi FT UGM. Kriteria minimal adalah adanya *letter of acceptance* dari penyelenggara seminar atau journal yang dimaksud dan bukti telah membayar biaya registrasi.

### Predikat Kelulusan

Mahasiswa yang dinyatakan lulus menerima predikat kelulusan sebagai berikut.

| Indek Prestasi | Keterangan |
|------------------------------------|------------------------------------|
| IP \> 3,75 | dengan pujian (“cum laude”), dengan masa studi maksimum 5 semester |
| 3,51 \< IP \< 3,75 | sangat memuaskan |
| 3,00 \< IP \< 3,51 | memuaskan |

: Indek Prestasi {#tbl-index tbl-colwidths="\[25,45\]"}

### **Pengulangan Matakuliah**

Untuk memperbaiki nilai mahasiswa diperkenankan mengambil kembali kegiatan pendidikan yang pernah diikuti dalam batas waktu studi yang diizinkan. Nilai yang dipergunakan untuk menghitung IP ialah nilai tertinggi yang pernah dicapainya.

### **Batas Waktu Studi**

Masa studi normal adalah 4 semester. Jenjang studi Magister harus dapat diselesaikan oleh mahasiswa dalam waktu selama-lamanya 1^1^/~2~ kali waktu yang ditentukan untuk menyelesaikan suatu jenjang studi.

Pada akhir batas waktu studi dilakukan evaluasi hasil studi. Apabila ternyata syarat-syarat penyelesaian jenjang Pasca Sarjana yang bersangkutan tidak dipenuhi, maka mahasiswa yang bersangkutan diminta untuk mengundurkan diri sebagai mahasiswa.

Mahasiswa diberi kesempatan untuk membuat surat permohonan perpanjangan studi satu semester kepada Dekan Fakultas Teknik UGM, dengan melampirkan keterangan yang diperlukan. Jika Dekan mengabulkan permohonan perpanjangan masa studi tersebut, maka mahasiswa diberi kesempatan untuk menyelesaikan studinya satu semester lagi.

### Cuti Kuliah

Mahasiswa diberi kesempatan untuk mengajukan cuti kuliah selama satu semester dengan membuat surat permohonan cuti kuliah beserta alasannya kepada Dekan Fakultas Teknik UGM. Jika permohonan cutinya dikabulkan, mahasiswa dapat melakukan cuti selama satu semester dan tidak perlu membayar SPP, dan status mahasiswa dalam sistem informasi akademis akan dibuat menjadi tidak aktif.

Mahasiswa yang akan aktif kuliah kembali, wajib membuat surat permohonan aktif  kuliah kepada Dekan Fakultas Teknik UGM, yang selanjutnya dapat digunakan sebagai kelengkapan syarat proses regestrasi.

### Matrikulasi

Agar mahasiswa baru sedini mungkin mempunyai gambaran yang jelas tentang Program Studi Magister Teknologi Informasi dan konsentrasi yang ada di dalamnya, maka sebelum kegiatan perkuliahan dimulai, dapat diadakan Program Matrikulasi kepada calon mahasiswa yang dirasa perlu, untuk  memberikan pemahaman terhadap pedoman akademik Program Studi Magister Teknologi Informasi.