---
date: "2026-07-08"
image-alt: "Prosedur pengajuan ujian susulan."
listing: false
toc: false
---

## Pengajuan Ujian Susulan {.unnumbered}

Mahasiswa yang berhalangan mengikuti ujian sesuai jadwal dan memenuhi persyaratan dapat mengajukan **Ujian Susulan** dengan prosedur sebagai berikut:

1.  **Unduh formulir permohonan** melalui laman **Pascasarjana DTETI** pada menu **Akademik → Permintaan Dokumen Akademik**:\
    <https://pasca.jteti.ugm.ac.id/>
2.  **Lengkapi formulir** dan lampirkan dokumen pendukung sesuai alasan pengajuan. Seluruh dokumen **dalam bentuk cetak (hardcopy)** diserahkan ke **Front Office Akademik DTETI Lantai 1**.

**Dokumen pendukung yang dapat diterima:**

-   **Sakit**: Surat keterangan/istirahat dari dokter.

-   **Musibah**: Surat keterangan dari instansi yang berwenang.

-   **Tugas Negara/Universitas/Fakultas/Program Studi**: Surat tugas resmi.

3.  Mahasiswa wajib **memantau jadwal pelaksanaan ujian susulan** yang akan diumumkan oleh Program Studi.

**Perhatian:**

-   Ujian susulan **hanya diberikan** kepada mahasiswa yang memenuhi ketentuan di atas dan melengkapi dokumen pendukung yang sah.

-   **Tidak ada ujian susulan untuk ujian susulan.** Oleh karena itu, mahasiswa wajib hadir pada jadwal ujian susulan yang telah ditetapkan.