# Pembiayaan Program Studi

Pembiayaan terdiri dari biaya operasional pendidikan, biaya penelitian, biaya pengabdian kepada masyarakat, biaya investasi SDM, sarana, dan prasarana, seperti yang ditunjukkan pada #tbl-detailcost. Pembiayaan berasal dari RKAT Departemen Teknik Elektro dan Teknologi Informasi, DIKTI dan mitra penelitian (baik dalam negeri maupun luar negeri).

| Jenis Penggunaan                           | Biaya (Rupiah) | \% Penggunaan |
|:-------------------------------------|----------------:|----------------:|
| Biaya operasional pendidikan               |  1.862.917.464 |          45,2 |
| Biaya penelitian                           |  1.733.394.793 |          42,1 |
| Biaya pengabdian kepada masyarakat         |     50.118.171 |           1,2 |
| Biaya investasi SDM, sarana, dan prasarana |    472.149.547 |          11,5 |

: Rincian Biaya Penggunaan Dana {#tbl-detailcost tbl-colwidths="\[60,25,15\]"}

Dari data yang disajikan terlihat bahwa alokasi dana untuk pengggunaan operasional pendidikan, penelitian, kegiatan PkM, dan investasi SDM dan sarana prasarana telah mencukupi untuk mendukung aktifitas tridharma Perguruan Tinggi di PMPSTI.